<?php

namespace TvShowManagerBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEpisodesWithShow() {
        $qb = $this->createQueryBuilder('e');

        $qb
            ->join('e.tvShow', 's')
            ->addSelect('s');

        return $qb->getQuery()->getResult();
    }
}
