<?php

namespace TvShowManagerBundle\Repository;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{
    public function findShowsWithEpisodes() {
        $qb = $this->createQueryBuilder('s');

        $qb
            ->join('s.episodes', 'e')
            ->addSelect('e');
    }
}
