<?php

namespace TvShowManagerBundle\Repository;

use TvShowManagerBundle\Entity\Episode;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{

    public function findShowsByAvgNote() {

        $qb = $this->createQueryBuilder('s')
            ->addSelect('AVG(e.note) AS avgNote')
            ->leftJoin('s.episodes', 'e')
            ->orderBy('avgNote', 'DESC')
            ->groupBy('s')
            ;

        return $qb->getQuery()->getResult();
    }

    // Atelier SQL / DQL / QB - Exercice 5
    public function find3WorstTvShowsQB() {

        $qb = $this->createQueryBuilder('s')
            ->addSelect('AVG(e.note) AS HIDDEN avg_note' )
            ->leftJoin('s.episodes', 'e')
            ->groupBy('s')
            ->orderBy('avg_note')
            ->setMaxResults(3)
        ;

        return $qb->getQuery()->getResult();
    }

    public function find3WorstTvShowsDQL() {

        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT s, AVG(e.note) AS HIDDEN avg_note
                  FROM TvShowManagerBundle:TvShow s
                  LEFT JOIN s.episodes e
                  GROUP BY s
                  ORDER BY avg_note'
        );
        $query->setMaxResults(3);

        return $query->getResult();
    }

    // Atelier SQL / DQL / QB - Exercice 7
    public function findLongestTvShowQB() {

        $qb = $this->createQueryBuilder('s')
            ->addSelect('COUNT(s) AS nb_episodes' )
            ->leftJoin('s.episodes', 'e')
            ->groupBy('s')
            ->orderBy('nb_episodes', 'DESC')
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getSingleResult();
    }

    public function findLongestTvShowDQL() {

        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT s, COUNT(s) AS nb_episodes
                  FROM TvShowManagerBundle:TvShow s
                  LEFT JOIN s.episodes e
                  GROUP BY s
                  ORDER BY nb_episodes DESC'
        );
        $query->setMaxResults(1);

        return $query->getSingleResult();
    }

    // Atelier SQL / DQL / QB - Exercice 8
    public function findTvShowsByYearQB($year) {

        $qb = $this->createQueryBuilder('s')
            ->where('s.year < :year')
            ->setParameter('year', $year)
        ;

        return $qb->getQuery()->getResult();
    }

    public function findTvShowsByYearDQL($year) {

        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT s
                  FROM TvShowManagerBundle:TvShow s
                  WHERE s.year < :year'
        );
        $query->setParameter('year', $year);

        return $query->getResult();
    }

}
