Checkpoint\TvShowManagerBundle\Entity\Episode:
    type: entity
    table: null
    repositoryClass: Checkpoint\TvShowManagerBundle\Repository\EpisodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        season:
            type: integer
        number:
            type: integer
        note:
            type: integer
        tvShow:
            type: string
            length: 255
    lifecycleCallbacks: {  }
