tv_show_manager:
    resource: "@TvShowManagerBundle/Resources/config/routing.yml"
    prefix:   /tvshow

subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

