tv_show_manager_homepage:
    path:     /
    defaults: { _controller: TvShowManagerBundle:Default:index }

tv_shows_list:
    path:     /shows
    defaults: { _controller: TvShowManagerBundle:TvShow:list }

tv_shows_add:
    path:     /shows/add
    defaults: { _controller: TvShowManagerBundle:TvShow:add }

tv_shows_show:
    path:     /shows/show/{name}
    defaults: { _controller: TvShowManagerBundle:TvShow:show }

tv_shows_edit:
    path:     /shows/edit/{name}
    defaults: { _controller: TvShowManagerBundle:TvShow:edit }

tv_shows_delete:
    path:     /shows/delete/{name}
    defaults: { _controller: TvShowManagerBundle:TvShow:delete }

episode_add:
    path:     /episodes/{name}/add
    defaults: { _controller: TvShowManagerBundle:Episode:add }

episode_edit:
    path:     /episodes/edit/{id}
    defaults: { _controller: TvShowManagerBundle:Episode:edit }

episode_delete:
    path:     /episodes/delete/{id}
    defaults: { _controller: TvShowManagerBundle:Episode:delete }

tv_shows_classement:
    path:     /shows/classement
    defaults: { _controller: TvShowManagerBundle:TvShow:note }

tv_shows_qb:
    path:     /qb/{num}
    defaults: { _controller: TvShowManagerBundle:Default:qb }