tvshow_index:
    path:     /
    defaults: { _controller: "WCSTvShowManagerBundle:TvShow:index" }
    methods:  GET

tvshow_show:
    path:     /{id}/show
    defaults: { _controller: "WCSTvShowManagerBundle:TvShow:show" }
    methods:  GET

tvshow_new:
    path:     /new
    defaults: { _controller: "WCSTvShowManagerBundle:TvShow:new" }
    methods:  [GET, POST]

tvshow_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSTvShowBundle:TvShow:edit" }
    methods:  [GET, POST]

tvshow_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSTvShowBundle:TvShow:delete" }
    methods:  DELETE

