<?php

namespace WCS\TvShowManagerBundle\Repository;
use WCS\TvShowManagerBundle\WCSTvShowManagerBundle;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTvShowByNote()
    {
        $query = $this->_em->createQuery(
            'SELECT t, AVG(e.note) note
                  FROM WCSTvShowManagerBundle:TvShow t
                  JOIN WCSTvShowManagerBundle:Episode e
                  WHERE t.id=e.tvshow
                  GROUP BY t.id
                  ORDER BY note DESC'
        );

        return $query->getResult();
    }
}
