<?php

namespace WCS\TvShowManagerBundle\Repository;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllSortedByNotes()
    {
        $querry =  $this->createQueryBuilder('tvShowTable')
            ->select('AVG(episodetable.note) AS moyNotes', 'tvShowTable')
            ->leftJoin('tvShowTable.episodes', 'episodetable')
            ->orderBy('moyNotes', 'DESC')
            ->groupBy('tvShowTable');

        return $querry->getQuery()->getResult();

    }
}
