
wcs_tv_show_manager_index:
    path:     /index
    defaults: { _controller: WCSTvShowManagerBundle:TvShow:index }

add:
    path:     /add
    defaults: { _controller: WCSTvShowManagerBundle:TvShow:add }

show:
    path:     /show/{id}
    defaults: { _controller: WCSTvShowManagerBundle:TvShow:show }

modify:
    path:     /modify/{id}
    defaults: { _controller: WCSTvShowManagerBundle:TvShow:modify }

delete:
    path:     /delete/{id}
    defaults: { _controller: WCSTvShowManagerBundle:TvShow:delete }